# Paths
yolo_root: data/archive
out_root: runs

# Training
img_size: 256
epochs: 30
batch: 64
lr: 0.0004
weight_decay: 0.0001
num_workers: 2
save_best_metric: macro_f1
freeze_backbone: false

# class_names:
#   - Ants
#   - Bees
#   - Beetles
#   - Caterpillars
#   - Earthworms
#   - Earwigs
#   - Grasshoppers
#   - Moths
#   - Slugs
#   - Snails
#   - Wasps
#   - Weevils

# Cropping
crop_margin_ratio: 0.07
min_crop_size: 10

# Misc
seed: 42